export interface Product {
  id: number
  name: string
  price: number
  originalPrice?: number
  image: string
  images: string[]
  rating: number
  reviews: number
  isOnSale: boolean
  category: string
  subcategory?: string
  description: string
  features: string[]
  colors: string[]
  sizes?: string[]
  inStock: boolean
  stockCount: number
}

export const products: Product[] = [
  // Clothing & Fashion
  {
    id: 101,
    name: "Colorful Tie-Strap Summer Dresses",
    price: 280,
    originalPrice: 350,
    image: "/images/dresses/tie-dresses.jpg",
    images: ["/images/dresses/tie-dresses.jpg", "/images/dresses/tie-dresses.jpg", "/images/dresses/tie-dresses.jpg"],
    rating: 4.8,
    reviews: 124,
    isOnSale: true,
    category: "Clothing",
    subcategory: "Women's Dresses",
    description:
      "Beautiful flowing dresses perfect for any occasion. These tie-strap summer dresses come in vibrant colors and are perfect for warm weather.",
    features: [
      "Adjustable tie straps",
      "Flowing silhouette",
      "Vibrant color options",
      "Comfortable fit",
      "Perfect for summer",
    ],
    colors: ["Green", "Beige", "Red", "Purple", "Pink"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    stockCount: 15,
  },
  {
    id: 102,
    name: "Ruffle Midi Dresses Collection",
    price: 320,
    originalPrice: 380,
    image: "/images/dresses/ruffle-dresses.jpg",
    images: [
      "/images/dresses/ruffle-dresses.jpg",
      "/images/dresses/ruffle-dresses.jpg",
      "/images/dresses/ruffle-dresses.jpg",
    ],
    rating: 4.9,
    reviews: 89,
    isOnSale: true,
    category: "Clothing",
    subcategory: "Women's Dresses",
    description: "Elegant ruffle dresses in vibrant colors. Perfect for special occasions and everyday elegance.",
    features: ["Ruffle detailing", "Midi length", "Premium fabric", "Flattering fit", "Versatile styling"],
    colors: ["Pink", "Blue", "Yellow", "Green"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    stockCount: 12,
  },
  {
    id: 103,
    name: "Flowing Maxi Dresses",
    price: 350,
    originalPrice: 420,
    image: "/images/dresses/maxi-dresses.jpg",
    images: [
      "/images/dresses/maxi-dresses.jpg",
      "/images/dresses/maxi-dresses.jpg",
      "/images/dresses/maxi-dresses.jpg",
    ],
    rating: 4.7,
    reviews: 156,
    isOnSale: true,
    category: "Clothing",
    subcategory: "Women's Dresses",
    description: "Comfortable and stylish maxi dresses perfect for any occasion.",
    features: ["Floor-length design", "Comfortable fabric", "Elegant silhouette", "Easy care", "Versatile styling"],
    colors: ["Black", "Navy", "Burgundy", "Emerald"],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    stockCount: 8,
  },
  {
    id: 104,
    name: "Cozy Turtleneck Collection",
    price: 247,
    originalPrice: 280,
    image: "/images/clothing/turtleneck-collection.jpg",
    images: [
      "/images/clothing/turtleneck-collection.jpg",
      "/images/clothing/turtleneck-collection.jpg",
      "/images/clothing/turtleneck-collection.jpg",
    ],
    rating: 4.8,
    reviews: 167,
    isOnSale: true,
    category: "Clothing",
    subcategory: "Tops & Blouses",
    description:
      "Soft and cozy turtleneck sweaters in multiple colors. Perfect for layering and staying warm in style.",
    features: [
      "Soft knit material",
      "Classic turtleneck design",
      "Multiple color options",
      "Comfortable fit",
      "Perfect for layering",
    ],
    colors: [
      "Beige",
      "Pink",
      "Lime Green",
      "Teal",
      "White",
      "Light Blue",
      "Purple",
      "Red",
      "Navy",
      "Cream",
      "Grey",
      "Black",
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
    inStock: true,
    stockCount: 25,
  },
  // Clothing - Activewear & Sets
  {
    id: 105,
    name: "High-Waisted Ribbed Leggings",
    price: 120,
    originalPrice: 150,
    image: "/images/clothing/leggings-tights.jpg",
    images: [
      "/images/clothing/leggings-tights.jpg",
      "/images/clothing/leggings-tights.jpg",
      "/images/clothing/leggings-tights.jpg",
    ],
    rating: 4.7,
    reviews: 189,
    isOnSale: true,
    category: "Clothing",
    subcategory: "Activewear & Leggings",
    description:
      "High-waisted ribbed leggings with tummy control. Perfect for workouts, casual wear, or lounging in comfort and style.",
    features: [
      "High-waisted design",
      "Ribbed texture",
      "Tummy control",
      "Stretchy comfortable fabric",
      "Perfect for workouts",
      "Versatile styling",
    ],
    colors: ["Grey", "Brown", "Black"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    stockCount: 30,
  },
  {
    id: 106,
    name: "2-Piece Crop Top & Legging Sets",
    price: 220,
    originalPrice: 280,
    image: "/images/clothing/2pcs-sets.jpg",
    images: ["/images/clothing/2pcs-sets.jpg", "/images/clothing/2pcs-sets.jpg", "/images/clothing/2pcs-sets.jpg"],
    rating: 4.8,
    reviews: 156,
    isOnSale: true,
    category: "Clothing",
    subcategory: "Activewear & Leggings",
    description:
      "Matching crop top and high-waisted legging sets. One size fits most. Perfect for workouts, casual outings, or lounging.",
    features: [
      "Matching crop top and leggings",
      "One size fits most",
      "Stretchy comfortable fabric",
      "Multiple color options",
      "Perfect for activewear",
      "Trendy crop top style",
    ],
    colors: ["White", "Hot Pink", "Black", "Burgundy", "Beige"],
    sizes: ["One Size"],
    inStock: true,
    stockCount: 25,
  },

  // Footwear
  {
    id: 301,
    name: "Classic Crocs - Beige",
    price: 350,
    originalPrice: 400,
    image: "/images/footwear/crocs-beige.jpg",
    images: [
      "/images/footwear/crocs-beige.jpg",
      "/images/footwear/crocs-beige.jpg",
      "/images/footwear/crocs-beige.jpg",
    ],
    rating: 4.7,
    reviews: 89,
    isOnSale: true,
    category: "Footwear",
    subcategory: "Casual Shoes",
    description:
      "Comfortable classic Crocs in beige with white accents. Perfect for everyday wear and outdoor activities.",
    features: [
      "Classic Crocs comfort",
      "Lightweight design",
      "Easy to clean",
      "Ventilation holes",
      "Adjustable heel strap",
    ],
    colors: ["Beige"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    inStock: true,
    stockCount: 15,
  },
  {
    id: 302,
    name: "Classic Crocs - Pink",
    price: 350,
    originalPrice: 400,
    image: "/images/footwear/crocs-pink.jpg",
    images: ["/images/footwear/crocs-pink.jpg", "/images/footwear/crocs-pink.jpg", "/images/footwear/crocs-pink.jpg"],
    rating: 4.8,
    reviews: 112,
    isOnSale: true,
    category: "Footwear",
    subcategory: "Casual Shoes",
    description: "Stylish pink Crocs with darker pink accents. A fun and comfortable choice for casual outings.",
    features: [
      "Classic Crocs comfort",
      "Vibrant pink color",
      "Lightweight design",
      "Easy to clean",
      "Ventilation holes",
    ],
    colors: ["Pink"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    inStock: true,
    stockCount: 12,
  },
  {
    id: 303,
    name: "Classic Crocs - Nude",
    price: 350,
    originalPrice: 400,
    image: "/images/footwear/crocs-nude.jpg",
    images: ["/images/footwear/crocs-nude.jpg", "/images/footwear/crocs-nude.jpg", "/images/footwear/crocs-nude.jpg"],
    rating: 4.6,
    reviews: 78,
    isOnSale: true,
    category: "Footwear",
    subcategory: "Casual Shoes",
    description: "Elegant nude-colored Crocs with pink accents. Perfect for a subtle, sophisticated look.",
    features: [
      "Classic Crocs comfort",
      "Neutral nude color",
      "Pink accent details",
      "Lightweight design",
      "Easy to clean",
    ],
    colors: ["Nude"],
    sizes: ["6", "7", "8", "9", "10", "11"],
    inStock: true,
    stockCount: 10,
  },
  {
    id: 304,
    name: "Teddy Bear Slippers",
    price: 220,
    originalPrice: 250,
    image: "/images/footwear/teddy-slippers.jpg",
    images: [
      "/images/footwear/teddy-slippers.jpg",
      "/images/footwear/teddy-slippers.jpg",
      "/images/footwear/teddy-slippers.jpg",
    ],
    rating: 4.9,
    reviews: 145,
    isOnSale: true,
    category: "Footwear",
    subcategory: "Slippers",
    description: "Adorable pink teddy bear slippers for kids. Soft, cozy, and perfect for keeping little feet warm.",
    features: [
      "Cute teddy bear design",
      "Soft plush material",
      "Non-slip sole",
      "Perfect for kids",
      "Machine washable",
    ],
    colors: ["Pink"],
    sizes: ["3", "4", "5", "6", "7", "8", "9"],
    inStock: true,
    stockCount: 20,
  },
  // Footwear - Slippers
  {
    id: 305,
    name: "Heart-Shaped Love Slippers",
    price: 180,
    originalPrice: 220,
    image: "/images/footwear/heart-slippers.jpg",
    images: [
      "/images/footwear/heart-slippers.jpg",
      "/images/footwear/heart-slippers.jpg",
      "/images/footwear/heart-slippers.jpg",
    ],
    rating: 4.8,
    reviews: 167,
    isOnSale: true,
    category: "Footwear",
    subcategory: "Slippers",
    description:
      "Adorable heart-shaped fuzzy slippers with 'Love' branding. Ultra-soft and comfortable for indoor wear.",
    features: [
      "Heart-shaped design",
      "Ultra-soft fuzzy material",
      "Love branding",
      "Non-slip sole",
      "Multiple color options",
      "Perfect for gifts",
    ],
    colors: ["Teal", "Pink", "Purple", "Red", "Grey"],
    sizes: ["36-37", "38-39", "40-41", "42-43"],
    inStock: true,
    stockCount: 25,
  },

  // Accessories - Handbags
  {
    id: 201,
    name: "Mesh Rhinestone Handbags",
    price: 100,
    originalPrice: 120,
    image: "/images/handbags/mesh-bags.jpg",
    images: ["/images/handbags/mesh-bags.jpg", "/images/handbags/mesh-bags.jpg", "/images/handbags/mesh-bags.jpg"],
    rating: 4.8,
    reviews: 124,
    isOnSale: true,
    category: "Accessories",
    subcategory: "Bags & Purses",
    description: "Sparkling mesh bags in multiple colors. Perfect for adding glamour to any outfit.",
    features: [
      "Rhinestone mesh design",
      "Multiple color options",
      "Adjustable chain strap",
      "Compact size perfect for essentials",
      "Eye-catching sparkle finish",
    ],
    colors: ["Purple", "Burgundy", "Black", "Orange", "Green", "Pink"],
    inStock: true,
    stockCount: 15,
  },
  {
    id: 202,
    name: "Structured Mini Bags",
    price: 100,
    originalPrice: 150,
    image: "/images/handbags/structured-bags.jpg",
    images: [
      "/images/handbags/structured-bags.jpg",
      "/images/handbags/structured-bags.jpg",
      "/images/handbags/structured-bags.jpg",
    ],
    rating: 4.9,
    reviews: 89,
    isOnSale: true,
    category: "Accessories",
    subcategory: "Bags & Purses",
    description: "Elegant structured bags for any occasion. Classic design meets modern functionality.",
    features: [
      "Structured design",
      "Premium materials",
      "Multiple carrying options",
      "Classic color palette",
      "Versatile styling",
    ],
    colors: ["White", "Black", "Pink", "Red"],
    inStock: true,
    stockCount: 12,
  },
  {
    id: 203,
    name: "Colorful Crossbody Bags",
    price: 100,
    originalPrice: 130,
    image: "/images/handbags/colorful-bags.jpg",
    images: [
      "/images/handbags/colorful-bags.jpg",
      "/images/handbags/colorful-bags.jpg",
      "/images/handbags/colorful-bags.jpg",
    ],
    rating: 4.6,
    reviews: 78,
    isOnSale: true,
    category: "Accessories",
    subcategory: "Bags & Purses",
    description: "Vibrant crossbody bags for everyday use. Perfect for hands-free convenience.",
    features: [
      "Adjustable crossbody strap",
      "Vibrant colors",
      "Multiple compartments",
      "Lightweight design",
      "Everyday functionality",
    ],
    colors: ["Red", "Blue", "Yellow", "Green", "Pink"],
    inStock: true,
    stockCount: 20,
  },
  {
    id: 204,
    name: "Canvas Character Totes",
    price: 80,
    originalPrice: 100,
    image: "/images/handbags/canvas-totes.jpg",
    images: [
      "/images/handbags/canvas-totes.jpg",
      "/images/handbags/canvas-totes.jpg",
      "/images/handbags/canvas-totes.jpg",
    ],
    rating: 4.6,
    reviews: 78,
    isOnSale: true,
    category: "Accessories",
    subcategory: "Bags & Purses",
    description: "Cute character-themed tote bags. Perfect for casual outings and everyday use.",
    features: [
      "Cute character design",
      "Durable canvas material",
      "Multiple color options",
      "Spacious interior",
      "Comfortable handles",
    ],
    colors: ["Black", "Pink", "Green", "Beige", "Blue"],
    inStock: true,
    stockCount: 20,
  },
  {
    id: 205,
    name: "Fluffy Heart Bag",
    price: 100,
    originalPrice: 120,
    image: "/images/handbags/heart-bag.jpg",
    images: ["/images/handbags/heart-bag.jpg", "/images/handbags/heart-bag.jpg", "/images/handbags/heart-bag.jpg"],
    rating: 4.9,
    reviews: 203,
    isOnSale: true,
    category: "Accessories",
    subcategory: "Bags & Purses",
    description:
      "Adorable heart-shaped fluffy bag with gold chain. A unique statement piece that's sure to turn heads.",
    features: [
      "Heart-shaped design",
      "Fluffy texture",
      "Gold chain strap",
      "Unique statement piece",
      "Instagram-worthy style",
    ],
    colors: ["White", "Pink"],
    inStock: true,
    stockCount: 5,
  },
  {
    id: 206,
    name: "Mini Structured Handbags",
    price: 160,
    originalPrice: 180,
    image: "/images/handbags/mini-bags.jpg",
    images: ["/images/handbags/mini-bags.jpg", "/images/handbags/mini-bags.jpg", "/images/handbags/mini-bags.jpg"],
    rating: 4.7,
    reviews: 95,
    isOnSale: true,
    category: "Accessories",
    subcategory: "Bags & Purses",
    description: "Compact structured bags in classic colors. Perfect for minimalist styling.",
    features: ["Mini size design", "Structured shape", "Premium materials", "Classic colors", "Elegant hardware"],
    colors: ["Black", "White", "Tan", "Navy"],
    inStock: true,
    stockCount: 10,
  },
  {
    id: 207,
    name: "Black Textured Shoulder Bag",
    price: 100,
    originalPrice: 120,
    image: "/images/handbags/black-textured.jpg",
    images: [
      "/images/handbags/black-textured.jpg",
      "/images/handbags/black-textured.jpg",
      "/images/handbags/black-textured.jpg",
    ],
    rating: 4.8,
    reviews: 67,
    isOnSale: true,
    category: "Accessories",
    subcategory: "Bags & Purses",
    description: "Elegant textured bag with chain detail. Perfect for sophisticated styling.",
    features: [
      "Textured leather finish",
      "Chain shoulder strap",
      "Magnetic closure",
      "Interior pockets",
      "Versatile styling",
    ],
    colors: ["Black"],
    inStock: true,
    stockCount: 8,
  },

  // Equipment & Beauty Tools
  {
    id: 501,
    name: "BLUEQUE Professional Nail Lamp",
    price: 250,
    originalPrice: 300,
    image: "/images/equipment/nail-lamp.jpg",
    images: ["/images/equipment/nail-lamp.jpg", "/images/equipment/nail-lamp.jpg", "/images/equipment/nail-lamp.jpg"],
    rating: 4.8,
    reviews: 156,
    isOnSale: true,
    category: "Equipment",
    subcategory: "Beauty Tools",
    description:
      "Professional UV/LED nail lamp for curing gel polish. Features 36W power and multiple timer settings for perfect manicures.",
    features: [
      "36W UV/LED technology",
      "Multiple timer settings",
      "Professional grade",
      "Compact design",
      "Easy to use",
      "Perfect for gel manicures",
    ],
    colors: ["White/Pink"],
    inStock: true,
    stockCount: 12,
  },
  {
    id: 502,
    name: "Portable Lint Remover",
    price: 150,
    originalPrice: 180,
    image: "/images/equipment/lint-remover.jpg",
    images: [
      "/images/equipment/lint-remover.jpg",
      "/images/equipment/lint-remover.jpg",
      "/images/equipment/lint-remover.jpg",
    ],
    rating: 4.6,
    reviews: 89,
    isOnSale: true,
    category: "Equipment",
    subcategory: "Household Tools",
    description:
      "Handheld fabric shaver and lint remover. Perfect for removing pills, lint, and fuzz from clothing and upholstery.",
    features: [
      "Portable handheld design",
      "Rechargeable battery",
      "Multiple fabric settings",
      "Easy to clean",
      "Compact size",
      "Effective lint removal",
    ],
    colors: ["White/Grey"],
    inStock: true,
    stockCount: 18,
  },
  // Equipment - Fitness & Organization
  {
    id: 503,
    name: "Multi-Tier Shoe Rack Organizer",
    price: 250,
    originalPrice: 300,
    image: "/images/equipment/shoe-rack.jpg",
    images: ["/images/equipment/shoe-rack.jpg", "/images/equipment/shoe-rack.jpg", "/images/equipment/shoe-rack.jpg"],
    rating: 4.6,
    reviews: 134,
    isOnSale: true,
    category: "Equipment",
    subcategory: "Storage & Organization",
    description:
      "Multi-tier metal shoe rack organizer. Perfect for organizing shoes, bags, and accessories. Includes wall hooks for additional storage.",
    features: [
      "Multi-tier design",
      "Metal construction",
      "Space-saving solution",
      "Easy assembly",
      "Holds multiple pairs of shoes",
      "Additional wall hooks included",
    ],
    colors: ["Silver/Black"],
    inStock: true,
    stockCount: 15,
  },
  {
    id: 504,
    name: "Waist Trainer Belt",
    price: 250,
    originalPrice: 300,
    image: "/images/equipment/waist-trainers.jpg",
    images: [
      "/images/equipment/waist-trainers.jpg",
      "/images/equipment/waist-trainers.jpg",
      "/images/equipment/waist-trainers.jpg",
    ],
    rating: 4.5,
    reviews: 198,
    isOnSale: true,
    category: "Equipment",
    subcategory: "Fitness & Wellness",
    description:
      "Professional waist trainer belt with adjustable compression. Features heat technology for enhanced results and comfortable wear.",
    features: [
      "Adjustable compression levels",
      "Heat technology",
      "Comfortable neoprene material",
      "Double velcro closure",
      "Supports back and posture",
      "Available in multiple sizes",
    ],
    colors: ["Black", "Pink"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
    stockCount: 20,
  },

  // Hair Care & Styling
  {
    id: 701,
    name: "Brazilian Curls Hair Treatment",
    price: 70,
    originalPrice: 90,
    image: "/images/haircare/brazilian-curls.jpg",
    images: [
      "/images/haircare/brazilian-curls.jpg",
      "/images/haircare/brazilian-curls.jpg",
      "/images/haircare/brazilian-curls.jpg",
    ],
    rating: 4.7,
    reviews: 234,
    isOnSale: true,
    category: "Hair Care",
    subcategory: "Hair Treatments",
    description:
      "UNIQUE Brazilian Curls treatment spray for all hair types. Enhances natural curls and provides long-lasting definition.",
    features: [
      "For all hair types",
      "Enhances natural curls",
      "Long-lasting definition",
      "Easy spray application",
      "Professional formula",
      "250ml bottle",
    ],
    colors: ["Pink"],
    inStock: true,
    stockCount: 25,
  },
  {
    id: 702,
    name: "IKT Hair Care Combo Set",
    price: 150,
    originalPrice: 200,
    image: "/images/haircare/ikt-combo.jpg",
    images: ["/images/haircare/ikt-combo.jpg", "/images/haircare/ikt-combo.jpg", "/images/haircare/ikt-combo.jpg"],
    rating: 4.8,
    reviews: 167,
    isOnSale: true,
    category: "Hair Care",
    subcategory: "Styling Products",
    description:
      "Complete IKT hair care set including foam hair wash, gel wax, and styling products for dynamic hairstyles.",
    features: [
      "Complete hair care set",
      "Foam hair wash included",
      "Gel wax for styling",
      "Professional quality",
      "Multiple products in one",
      "Perfect for all hair types",
    ],
    colors: ["Gold/Black"],
    inStock: true,
    stockCount: 15,
  },

  // Beauty & Personal Care
  {
    id: 401,
    name: "Hydrating Face Serum",
    price: 150,
    originalPrice: 220,
    image: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    rating: 4.8,
    reviews: 89,
    isOnSale: true,
    category: "Beauty",
    subcategory: "Skincare",
    description: "Nourishing serum for all skin types. Provides deep hydration and anti-aging benefits.",
    features: [
      "Hyaluronic acid formula",
      "All skin types",
      "Anti-aging properties",
      "Deep hydration",
      "Lightweight texture",
    ],
    colors: ["Clear"],
    inStock: true,
    stockCount: 25,
  },
  {
    id: 402,
    name: "Luxury Lipstick Collection",
    price: 80,
    originalPrice: 120,
    image: "/placeholder.svg?height=300&width=300",
    images: [
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
      "/placeholder.svg?height=300&width=300",
    ],
    rating: 4.9,
    reviews: 156,
    isOnSale: true,
    category: "Beauty",
    subcategory: "Makeup",
    description: "Premium lipsticks in various shades. Long-lasting formula with rich pigmentation.",
    features: [
      "Long-lasting formula",
      "Rich pigmentation",
      "Moisturizing ingredients",
      "Variety of shades",
      "Luxury packaging",
    ],
    colors: ["Red", "Pink", "Nude", "Berry", "Coral"],
    inStock: true,
    stockCount: 30,
  },
  {
    id: 403,
    name: "Sexy Night Body Mist",
    price: 150,
    originalPrice: 180,
    image: "/images/beauty/body-mist.jpg",
    images: ["/images/beauty/body-mist.jpg", "/images/beauty/body-mist.jpg", "/images/beauty/body-mist.jpg"],
    rating: 4.7,
    reviews: 198,
    isOnSale: true,
    category: "Beauty",
    subcategory: "Fragrances",
    description:
      "Luxurious Body Philosophy Sexy Night body mist. Elegant burgundy bottles with gold accents and captivating fragrance.",
    features: [
      "Long-lasting fragrance",
      "Elegant packaging",
      "250ml bottle",
      "Premium quality",
      "Sophisticated scent",
      "Perfect for evening wear",
    ],
    colors: ["Burgundy"],
    inStock: true,
    stockCount: 20,
  },

  // Drinkware & Accessories
  {
    id: 801,
    name: "Stanley Quencher H2O Tumbler",
    price: 300,
    originalPrice: 350,
    image: "/images/drinkware/stanley-tumbler.jpg",
    images: [
      "/images/drinkware/stanley-tumbler.jpg",
      "/images/drinkware/stanley-tumbler.jpg",
      "/images/drinkware/stanley-tumbler.jpg",
    ],
    rating: 4.9,
    reviews: 267,
    isOnSale: true,
    category: "Drinkware",
    subcategory: "Tumblers",
    description:
      "Authentic Stanley Quencher H2O Tumbler 40oz. The ultimate hydration companion with all-day ice retention.",
    features: [
      "40oz capacity",
      "All-day ice retention",
      "Leak-proof design",
      "Fits in car cup holders",
      "Durable construction",
      "Authentic Stanley quality",
    ],
    colors: ["White"],
    inStock: true,
    stockCount: 8,
  },
  {
    id: 802,
    name: "Colorful Insulated Tumblers",
    price: 200,
    originalPrice: 250,
    image: "/images/drinkware/plain-tumblers.jpg",
    images: [
      "/images/drinkware/plain-tumblers.jpg",
      "/images/drinkware/plain-tumblers.jpg",
      "/images/drinkware/plain-tumblers.jpg",
    ],
    rating: 4.6,
    reviews: 145,
    isOnSale: true,
    category: "Drinkware",
    subcategory: "Tumblers",
    description:
      "Stylish insulated tumblers with handles in multiple colors. Perfect for hot and cold beverages on the go.",
    features: [
      "Double-wall insulation",
      "Comfortable handle",
      "Multiple color options",
      "Leak-proof lid",
      "Easy to clean",
      "Perfect for travel",
    ],
    colors: ["Black", "Peach", "White", "Purple", "Hot Pink", "Light Pink", "Lavender", "Blue"],
    inStock: true,
    stockCount: 30,
  },

  // Home & Household
  {
    id: 601,
    name: "Fluffy Decorative Cushions",
    price: 120,
    originalPrice: 150,
    image: "/images/home/fluffy-cushions.jpg",
    images: [
      "/images/home/fluffy-cushions.jpg",
      "/images/home/fluffy-cushions.jpg",
      "/images/home/fluffy-cushions.jpg",
    ],
    rating: 4.8,
    reviews: 134,
    isOnSale: true,
    category: "Household",
    subcategory: "Home Decor",
    description: "Ultra-soft fluffy cushions in vibrant colors. Perfect for adding comfort and style to any room.",
    features: [
      "Ultra-soft fluffy texture",
      "Multiple vibrant colors",
      "Perfect for home decor",
      "Comfortable and cozy",
      "Easy to maintain",
    ],
    colors: ["White", "Red", "Lime Green", "Grey", "Blue", "Orange", "Pink", "Purple", "Turquoise"],
    inStock: true,
    stockCount: 30,
  },
  {
    id: 602,
    name: "Butterfly Wall Stickers",
    price: 80,
    originalPrice: 100,
    image: "/images/home/wall-stickers.jpg",
    images: ["/images/home/wall-stickers.jpg", "/images/home/wall-stickers.jpg", "/images/home/wall-stickers.jpg"],
    rating: 4.5,
    reviews: 89,
    isOnSale: true,
    category: "Household",
    subcategory: "Home Decor",
    description:
      "Beautiful butterfly wall decals in pink and silver. Easy to apply and remove, perfect for decorating any room.",
    features: [
      "Easy to apply and remove",
      "No damage to walls",
      "Pink and silver butterflies",
      "Multiple sizes included",
      "Perfect for any room",
      "Reusable design",
    ],
    colors: ["Pink", "Silver"],
    inStock: true,
    stockCount: 25,
  },
  // Home & Household - Rugs & Mats
  {
    id: 603,
    name: "Fluffy Area Rugs Collection",
    price: 180,
    originalPrice: 220,
    image: "/images/home/fluffy-mats.jpg",
    images: ["/images/home/fluffy-mats.jpg", "/images/home/fluffy-mats.jpg", "/images/home/fluffy-mats.jpg"],
    rating: 4.7,
    reviews: 234,
    isOnSale: true,
    category: "Household",
    subcategory: "Rugs & Mats",
    description:
      "Ultra-soft fluffy area rugs in multiple colors. Perfect for living rooms, bedrooms, or any space that needs comfort and style.",
    features: [
      "Ultra-soft fluffy texture",
      "Multiple size options",
      "Wide range of colors",
      "Non-slip backing",
      "Easy to clean",
      "Perfect for any room",
    ],
    colors: [
      "Green",
      "Red",
      "Pink",
      "Lime",
      "Black",
      "Grey",
      "Purple",
      "Burgundy",
      "Teal",
      "Brown",
      "Beige",
      "White",
      "Navy",
      "Orange",
    ],
    sizes: ["Small", "Medium", "Large"],
    inStock: true,
    stockCount: 40,
  },
]

export function getProductById(id: number): Product | undefined {
  return products.find((product) => product.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((product) => product.category.toLowerCase() === category.toLowerCase())
}
